network:
  ip: 209.97.189.19
  # ip: 192.168.100.0
  cidr: 24
  exempt:
  - 192.168.8.24
  - 192.168.1.12
  - 192.168.6.10
  - 192.168.8.16
  snmp:
    port: 161
    v2:
      community: public
    v3:
      auth_key: authkey1
      priv_key: privkey1
      user: usr-sha-aes128
runtime:
  # mode: network
  mode: agent
  export: True
  export_path: '/Users/elaunick/Projects/GITS/Watchmanagent/watchman_agent/'
  export_type: 'json'
  client_id: g6wW5YVrD6J3IwvY6DB4jEyq7iGQkVHJhwyDYHc0
  secret_key: VGwDqOAT6CgtoPQL1WUCcsyBZiMHbXEHaXGQS1EQbyzOnbWTanTC6QVNrM4m
schedule:
  day: '*'
  hour: '*'
  minute: 30
  month: 12
