network:
  cidr: 24
  exempt:
  - 192.168.1.12
  - 192.168.6.10
  - 192.168.8.16
  - 192.168.8.24
  ip: 192.168.100.0
  snmp:
    port: 161
    v2:
      community: public
    v3:
      auth_key: authkey1
      priv_key: privkey1
      user: usr-sha-aes128
runtime:
  client_id: g6wW5YVrD6J3IwvY6DB4jEyq7iGQkVHJhwyDYHc0
  export: false
  export_file: watchman_export_assets.csv
  export_path: /home/near
  mode: agent
  secret_key: VGwDqOAT6CgtoPQL1WUCcsyBZiMHbXEHaXGQS1EQbyzOnbWTanTC6QVNrM4m
schedule:
  day: '*'
  hour: '*'
  minute: 30
  month: 12
