runtime:
  mode: 'agent' # 'network'
  client_id: "g6wW5YVrD6J3IwvY6DB4jEyq7iGQkVHJhwyDYHc0"
  secret_key: "VGwDqOAT6CgtoPQL1WUCcsyBZiMHbXEHaXGQS1EQbyzOnbWTanTC6QVNrM4m"
schedule:
  hours: 12
  days: 1
  minutes: 30
  secondes: 20
network:
  cidr: 24
  ip: 192.168.0.0
  excempt: ['192.168.6.10', '192.168.8.16', '192.168.6.10']
  community: 'public'